# Generated by Django 3.2.15 on 2022-09-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyundai_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagebanner',
            name='tags',
        ),
    ]
