# Generated by Django 3.2.15 on 2022-09-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyundai_app', '0002_remove_mainpagebanner_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagebanner',
            name='active',
        ),
        migrations.RemoveField(
            model_name='mainpagebanner',
            name='body',
        ),
        migrations.RemoveField(
            model_name='mainpagebanner',
            name='featured',
        ),
    ]
