# Generated by Django 3.2.15 on 2022-09-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyundai_app', '0003_auto_20221001_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Name', models.CharField(max_length=200)),
                ('Model_Price', models.CharField(blank=True, max_length=200, null=True)),
                ('Images', models.ImageField(blank=True, null=True, upload_to='img')),
                ('Fuel', models.TextField(max_length=20)),
                ('Engine', models.TextField(max_length=20)),
                ('AWD_RWD', models.TextField(max_length=20)),
            ],
        ),
    ]
