# Generated by Django 3.2.15 on 2022-09-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyundai_app', '0005_stockcars_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcars',
            name='AWD_RWD',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockcars',
            name='Engine',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockcars',
            name='Fuel',
            field=models.CharField(max_length=20),
        ),
    ]
