# Generated by Django 3.2.16 on 2022-10-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyundai_app', '0007_modelscars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelscars',
            name='Image',
            field=models.CharField(max_length=300),
        ),
    ]
